name: CI

on:
  pull_request:
  push:
    branches: [main]

# cancels old executions from the same branch/PR
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Lint • Typecheck • Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Prettier check
        run: npm run format:check

      - name: ESLint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        env:
          NODE_ENV: production
        run: npm run build
